{
 "title": "API scrape health",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Emails Failed Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "emails_failed_total", "legendFormat": "__auto" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Avg Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(email_processing_duration_seconds_sum[1m]) / rate(email_processing_duration_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Emails sent total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "emails_sent_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Emails Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    { "expr": "rate(emails_failed_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Emails Sennt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    { "expr": "rate(emails_sent_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "API scrape health",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"newsletter-api\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}